version: '3.8'

services:
  backend:
    build: ./BotaaS-Server
    ports:
      - "8000:8000"
    volumes:
      - ./BotaaS-Server:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/botaas
      - DEBUG=True
    depends_on:
      - db
    networks:
      - botaas-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./BotaaS-Website
    ports:
      - "4200:4200"
    volumes:
      - ./BotaaS-Website:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - botaas-network
    command: ng serve --host 0.0.0.0 --port 4200

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=botaas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - botaas-network

networks:
  botaas-network:
    driver: bridge

volumes:
  postgres_data: